# Prism AI Backend - Development Docker Compose
# Development environment with hot reload and debug features

version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.fast
      cache_from:
        - python:3.12-slim
        - prism-ai-backend:cache
    container_name: prism-ai-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Development Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=development
      - DEBUG=true
      - SECRET_KEY=development-secret-key-not-for-production
      - SERVER_URL=http://localhost:8000
      
      # OpenAI Configuration (use development key)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4-turbo
      - OPENAI_MAX_TOKENS=4000
      - OPENAI_TEMPERATURE=0.1
      
      # CORS Configuration (allow all for development)
      - ALLOWED_ORIGINS=*
      
      # File Processing Configuration
      - TEMP_DIR=/app/temp
      - BATCH_SIZE=20
      - MAX_FILE_SIZE=100
      - MAX_ROWS_PER_FILE=10000
      
      # Performance Configuration (smaller for dev)
      - FTT_ML_CORES=4
      - MEMORY_LIMIT_GB=8
      - CHUNK_SIZE=1000
      
      # Logging Configuration
      - LOG_LEVEL=debug
      
      # Development Features
      - RELOAD=true
      - WORKERS=1
      
    volumes:
      # Mount source code for hot reload
      - ./app:/app/app:ro
      - ./test:/app/test:ro
      - backend-dev-temp:/app/temp
      - ./logs:/app/logs
      
    networks:
      - prism-ai-dev-network
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
      
    command: >
      sh -c "python -m uvicorn app.main:app 
             --host 0.0.0.0 
             --port 8000 
             --reload 
             --reload-dir app 
             --log-level debug"

  # Development database (SQLite or PostgreSQL)
  dev-db:
    image: postgres:15-alpine
    container_name: prism-ai-dev-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prism_ai_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - prism-ai-dev-network
    profiles:
      - database

  # Development Redis
  dev-redis:
    image: redis:alpine
    container_name: prism-ai-dev-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - dev-redis-data:/data
    networks:
      - prism-ai-dev-network
    profiles:
      - redis

  # Optional: MinIO for S3-compatible storage testing
  minio:
    image: minio/minio
    container_name: prism-ai-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    networks:
      - prism-ai-dev-network
    command: server /data --console-address ":9001"
    profiles:
      - storage

networks:
  prism-ai-dev-network:
    driver: bridge

volumes:
  backend-dev-temp:
    driver: local
  dev-db-data:
    driver: local
  dev-redis-data:
    driver: local
  minio-data:
    driver: local